language: node_js
node_js:
- node
- 6
env:
  global:
    - CXX=g++-4.8
    - MONGODB_VERSION=3.4.4
before_install:
  - npm install -g npm@latest

install:
  - export CXX="g++-4.8"
  - npm install

services:
- mongodb
addons:
  apt:
    sources:
    # - mongodb-3.4
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    # - mongodb-org-server
before script:  
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=3.4.4 mongodb-org-server=3.4.4 mongodb-org-shell=3.4.4 mongodb-org-mongos=3.4.4 mongodb-org-tools=3.4.4
  - sleep 15 #mongo may not respond immediatly
  - mongo --version
script: npm run coverage
