language: node_js
before_install:
  npm install -g npm@'>=1.4.3'
node_js:
- node
- 6
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.4-precise
    packages:
    - mongodb-org-server
script: npm run coverage
